# Generated by Django 5.0.6 on 2024-08-05 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.CharField(max_length=50, unique=True)),
                ('image_url', models.URLField()),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('breed', models.CharField(blank=True, max_length=100, null=True)),
                ('is_favorite', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'cat',
            },
        ),
        migrations.CreateModel(
            name='FavoriteCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.cat')),
            ],
            options={
                'db_table': 'favorite_cat',
            },
        ),
    ]
